<?php

    $users = array (
        "MatWasTaken" => array (
            "name" => "Matteo",
            "surname" => "Veronesi",
            "age" => 18,
            "password" => "1234",
            "accesses" => 0
        ),
        "SimonSays" => array (
            "name" => "Simone",
            "surname" => "Ceschi",
            "age" => 18,
            "password" => "5678",
            "accesses" => 0
        ),
        "TheGreat" => array (
            "name" => "Giuseppe",
            "surname" => "Rossi",
            "age" => 20,
            "password" => "IAmGreat",
            "accesses" => 5
        ),
        "Thasup" => array (
            "name" => "Davide",
            "surname" => "Mattei",
            "age" => 24,
            "password" => "0hG0d238451",
            "accesses" => 7
        ),
        "Guest" => array (
            "name" => "Guest",
            "surname" => "",
            "age" => 0,
            "password" => "",
            "accesses" => 0
        ),
        
    );
   
    $songs = [
        [
            "name" => "scuol4",
            "artist" => "Thasup",
            "key" => "A minor",
            "bpm" => 102,
            "duration" => "2:50",
            "release date" => "2018-06-08",
            "album" => "23 6451",
            "immagine"=>"./images/scuol4.jpg",
            "lyrics"=>"
    Yah, yah, ah, yah
    Io che non andavo a scuola, uh
    Mamma mi chiamava, mi diceva: \"Che fai?\", entro in seconda ora, yah
    Ma poi non entravo, tra mille pensieri, quindi sbuffo marijuana
    Quindi figlio di puttana, sta lontano dai miei guai
    Non ti conto proprio, no, parli e dico: \"Ok\"
    Ma mi sentivo un po' sprecato a scuola, uh
    Mamma già sapeva, dai, ma poi che importa se mi prendo una sbroccata? Yah
    Lì no, non c'entravo, ho lasciato stare quando ho visto una puttana
    Quindi, figlio di puttana, sta lontano dai miei guai
    Non ti conto proprio, no, parli e dico: \"Ok\"
    Ma mi sentivo un po' sprecato a scuola, yah
    Sempre all'ultimo banco, uh, le formule non le so, yah
    Non puoi dirmi di no, non distrarmi se poi quando parlo ti fotto, uh
    Troppo easy, mille grazie, yah, troppi, troppi finti \"Come va?\"
    Vaffanculo e dimmi ora che ti serve che godo a dirti no
    Come sto? Non lo so e se lo so
    Lo vengo a dire a te che parli dietro
    Come no, dico boh, non ci sto e se ci sto
    Con quelli come te io resto freddo, yah, uh
    Venti chiamate perse, non mi inculo nessuno, ah
    La testa mi esplode, il cell pure, yah
    Io che non andavo a scuola, uh
    Mamma mi chiamava, mi diceva: \"Che fai?\", entro in seconda ora, yah
    Ma poi non entravo, tra mille pensieri, quindi sbuffo marijuana
    Quindi figlio di puttana, sta lontano dai miei guai
    Non ti conto proprio, no, parli e dico: \"Ok\"
    Ma mi sentivo un po' sprecato a scuola, uh
    Mamma già sapeva, dai, ma poi che importa se mi prendo una sbroccata? Yah
    Lì no, non c'entravo, ho lasciato stare quando ho visto una puttana
    Quindi, figlio di puttana, sta lontano dai miei guai
    Non ti conto proprio, no, parli e dico: \"Ok\"
    Ma mi sentivo un po' sprecato a scuola, yah
    Bro, ma aspetta un istante
    Ma di cosa stai parlando?
    Per essere tuo amico devo vestirmi così?
    Ma proprio col cazzo, ehi
    Guarda, bro, piuttosto non mi vesto
    Rido, ahah, non ti cago, non ti penso
    Grazie mamma che mi ha fatto un po' diverso
    Bella trama, bella merda, se ci penso
    Resto perso tra mille pensieri, yah, yeah
    E tu che mi dici come fare
    Non ti ascolto proprio, no, fra', yeah
    Guarda dove sono senza te, fra' (ehi, yah, ma)
    Io che non andavo a scuola, uh
    Mamma mi chiamava, mi diceva: \"Che fai?\", entro in seconda ora, yah
    Ma poi non entravo, tra mille pensieri, quindi sbuffo marijuana
    Quindi figlio di puttana, sta lontano dai miei guai
    Non ti conto proprio, no, parli e dico: \"Ok\"
    Ma mi sentivo un po' sprecato a scuola, uh
    Mamma già sapeva, dai, ma poi che importa se mi prendo una sbroccata? Yah
    Lì no, non c'entravo, ho lasciato stare quando ho visto una puttana
    Quindi, figlio di puttana, sta lontano dai miei guai
    Non ti conto proprio, no, parli e dico: \"Ok\"
    Ma mi sentivo un po' sprecato a scuola, yah (Uh)
    Ma mi sentivo un po' sprecato a scuola, yah (Eh-eh, eh-eh, eh)
    Ok, ma mi sentivo un po' sprecato a scuola, yah (Uh)
    Ma mi sentivo un po' sprecato a scuola "
        ],
        [
            "name"=>"one king",
            "artist" => "Tha Sup e Mara Sattei",
            "key" => "C major",
            "bpm" => 105,
            "duration" => "2:31",
            "release date" => "2024-12-13",
            "album" => "Casa Gospel",
            "immagine"=>"./images/oneKing.jpg",
            "lyrics"=>"
    One king, non ti fare cambiare mai dagli altri
    Oggi sanno che lui potrà cambiarti
    Ossia, in questa via di passi falsi
    La mia strada sarà quella più avanti
    Non ti fare cambiare mai dagli altri
    Oggi sanno che lui potrà cambiarti
    Ossia, in questa via di passi falsi (yeah, yeah, yeah)
    La mia strada sarà quella più avanti
    Mi inchino solo per arrivare agli altri (agli altri)
    Non ti dico quanti snitch in questo party (party)
    Qualcuno prima o poi si farà del male
    Okay, okay, non ti passa se chiami mayday
    Ma mi passa se amo una lei che riposa dentro ai sogni miei
    Okay, okay, con lo sguardo mi dici: \"Son fake\"
    Con lo sguardo mi dici: \"Vorrei, ma non posso\", too late, too late
    Vorrei più space, più J, più take, più hopes
    Che presto sarà okay, io non potrei
    Mai chiamare qualcun altro col nome di re
    Tutti vogliono esserlo, ma guarda che uno ce n'è
    One king, non ti fare cambiare mai dagli altri
    Oggi sanno che lui potrà cambiarti
    Ossia, in questa via di passi falsi
    La mia strada sarà quella più avanti
    Non ti fare cambiare mai dagli altri
    Oggi sanno che lui potrà cambiarti
    Ossia, in questa via di passi falsi
    La mia strada sarà quella più avanti
    Sempre in alto mare, in tempesta qui per respirare
    Tu pensa pure a quanti affanni, tu pensa a tutte le pare
    Io dentro vedo un alveare con vuoti che ho da colmare
    Con pensieri al collare, che pessima idea volare
    Mi sa che tra i bivi io penso: \"Sarò viva?\"
    Ho mille obiettivi e saldi principi
    Non contano i dindi, ma di chi poi ti fidi
    In testa ho gli archivi, ma in cuore ho gli scrigni
    Non mi importa, cosa parli? È una bugia
    Alla fine siamo in tanti, non sei più real
    Io non ho capito ancora questa follia
    Ma non mi appartiene, non è più la mia
    One king, non ti fare cambiare mai dagli altri
    Oggi sanno che lui potrà cambiarti
    Ossia, in questa via di passi falsi
    La mia strada sarà quella più avanti
    Non ti fare cambiare mai dagli altri
    Oggi sanno che lui potrà cambiarti
    Ossia, in questa via di passi falsi
    La mia strada sarà quella più avanti"
        ],
        [
            "name"=>"sciroppo",
            "artist" => "Sfera",
            "key" => "F♯ major",
            "bpm" => 162,
            "duration" => "3:25",
            "release date" => "2018-01-19",
            "album" => "Rockstar",
           "immagine"=>"./images/sciroppo.jpg",
            "lyrics"=>"Sciroppo cade basso come l'MD
    Io non cado in basso, sono ancora in piedi
    Puoi trovarmi il lunedì, martedì
    Mercoledì, giovedì, venerdì, ehi
    Sciroppo cade basso come l'MD
    Io non cado in basso, sono ancora in piedi
    Puoi trovarmi il lunedì, martedì
    Mercoledì, giovedì sempre sulla stessa wave
    Sciroppo cade basso come l'MD
    Io non cado in basso, sono ancora in piedi
    Puoi trovarmi il lunedì, martedì
    Mercoledì, giovedì sempre sulla stessa wave
    KNGL, io non cambio bandiera
    Sono Francesco Totti e Alex Del Piero
    Solo facendo soldi senza più pensieri
    Sempre perenne rolling quando arriva sera
    Sciroppo cade basso come l'MD
    Bevo solo Makatussin nel bicchiere
    Solo 20 anni che in questo mondo sto in piedi
    Non è che sono rimasto con 20 denti, ya-ya
    Non parlarmi a me se sei un incompetente, ya-ya
    Corro con la bitch verso il flow che faccio meta, ya-ya
    Lo sai che non sono la concorrenza
    Puoi chiamare a me, parlare a me, dirmi le tue esperienze, ok
    Eh-eh, eh-eh, eh-eh, eh-eh
    Gigi sopra il beat, c'è chi ha fatto finta di niente
    Faccio eh-eh, eh-eh, eh-eh, eh-eh
    Ah uh ah, le parole sono semplici, okay!
    Sciroppo cade basso come l'MD
    Io non cado in basso, sono ancora in piedi
    Puoi trovarmi il lunedì, martedì
    Mercoledì, giovedì sempre sulla stessa wave
    Sciroppo cade basso come l'MD
    Io non cado in basso, sono ancora in piedi
    Puoi trovarmi il lunedì, martedì
    Mercoledì, giovedì sempre sulla stessa wave
    Droga, moda, rosa la mia soda
    Chiama Uber per tornare in zona
    Noi non contiamo niente, ma ne contiamo tanti
    Billion Headz Money Money Money
    Non conosco nessuno che ammazza la squad
    La tipa che mi scopo si ammazza di squat
    Sciroppo all'amarena, c'ho la gola secca, ehi
    Lei è rimasta a bocca aperta, uh
    Bling come una star, K nella smart
    Rollo sei grammi sopra l'IPad, uh yah
    Mi odia il suo chihuahua
    E come te abbaia, il mio collo ti abbaglia
    Sciroppo cade basso come l'MD
    Io non cado in basso, sono ancora in piedi
    Puoi trovarmi il lunedì, martedì
    Mercoledì, giovedì, venerdì, ehi
    Sciroppo cade basso come l'MD
    Io non cado in basso, sono ancora in piedi
    Puoi trovarmi il lunedì, martedì
    Mercoledì, giovedì sempre sulla stessa wave
    Sciroppo cade basso come l'MD
    Io non cado in basso, sono ancora in piedi
    Puoi trovarmi il lunedì, martedì
    Mercoledì, giovedì sempre sulla stessa wave
    Sempre sulla stessa wave
    Sempre sulla stessa wave"
        ],
        [
            "name"=>"dende",
            "artist" => "Ghali",
            "key" => "F♯ major",
            "bpm" => 140,
            "duration" => "3:30",
            "release date" => "2017-11-24",
            "album" => "Lunga vita a sto",
            "immagine"=>"./images/dende.jpg",
            "lyrics"=>"
    Sto
    Sto
    I miei frate fuori come ombrelli nell'atrio
    Affogo nel mio drink come Leonardo DiCaprio
    Passaporto rouge valido per l'espatrio
    Palme storte copron la mia testa su un BMW
    Fluttuo nell'aria, uh-la-la
    Di Goku ce n'è uno, sei Mr. Satan
    Il tuo entourage frate è in ramadan
    Sparisci, Abra Kadabra, puff, Alakazam
    L'industria è un tritacarne, io sono halal
    Il flow è turbofuoco, scelgo Charliezard
    Mi chiedi da dove vengo? Baggio Boulevard
    Karma è l'unica tipa che torna come un boomerang
    Sto nella mia bolla, sto nella mia bolla
    La mia mano è Jimmy, no no, non sono le corna
    Ti sto insegnando a farlo, sputa quella gomma
    Un po' di rispetto, insomma
    Non vedi che sono verde
    Fumo Namecc, scusami Dende
    La squadra è in attacco, qua nessuno difende
    Non dirmi che vai, resta o mi scende
    Non vedi che sono verde
    Fumo Namecc, scusami Dende
    La squadra è in attacco, qua nessuno difende
    Non dirmi che vai, resta o mi scende
    Esco come Billie Jean!
    Tu mi dici Billie che?
    Piccolezze minime
    Vedo solo mini me
    Fu-fu-fu-fuck la tua baby-gang
    Occhiali sopra i miei Babybel
    Bla bla bla shhh, non vedi che
    Ghali Bomaye
    Me la piglio con tutti, mi piglio con quello
    Mi piglio frate' con chi cazzo mi pare
    Tu dimmi chi sei frate per giudicare
    Ma fanculo te e le tue cazzo di pare
    Ma dai molla l'osso
    'Sti rapper li disosso
    Registro più pezzi che posso
    Se crepo o succede qualcosa sto apposto
    Come dopo lo squillo \"Frate' son pronto\"
    Muove il dito Jenny non è morto
    Veneziano ti guardo, coda dell'occhio
    Non fumare da solo, lasciami un morso
    Kunta Kinte, senza gambe corro
    Dietro le quinte con gli occhi bordeaux
    Quando arriviamo è bordello in corso
    La plata o lo plomo, frà scusa posso?
    La plata o lo plomo, frà scusa posso?
    Frà, tutto bene? Ti vedo rosso
    Non sono fatto, sono solo mosso
    Rifacciamo?
    Non vedi che sono verde
    Fumo Namecc, scusami Dende
    La squadra è in attacco, qua nessuno difende
    Non dirmi che vai, resta o mi scende
    Non vedi che sono verde
    Fumo Namecc, scusami Dende
    La squadra è in attacco, qua nessuno difende
    Non dirmi che vai, resta o mi scende
    Non vedi che sono cotto, dai
    Come un coccodrillo con la krokodil
    Chi è il migliore? Dillo, tu mi batterai
    Il giorno che vedrai Salvini ai miei live"
        ],
        [
            "name"=>"veleno 6",
            "artist" => "MadMan",
            "key" => "D major",
            "bpm" => 148,
            "duration" => "3:25",
            "release date" => "2016-10-27",
            "album" => "MM Volume 2 Mixtape",
            "immagine"=>"./images/veleno6.jpg",
            "lyrics"=>"
    È il Gemitaiz te rispondo ancora che voi?
    C'ho ancora un po' de veleno pe' voi
    Punta ai grattacieli come la Bad Boy
    Flow Makaveli, calo col match point
    Il mio flow per te è una tortura
    Puoi portare chi ti pare tanto non dura
    Fuori bianchi dentro negri come in Honduras
    Ne facciamo finchè ci schiantiamo col tour bus
    Quando entro sulla base questi ancora che mi guardano
    Non sono capaci quindi gridano allo scandalo
    Sulle basi lente faccio il vandalo
    Ricorda che sono una Jordan, tu sei il sandalo
    Con due etti divento E.T
    Sotto funghetti, se mi permetti
    Metto i lucchetti sopra i versetti
    Solo se smetti ci fai contenti
    Check it, check it, frate' fammi provare
    Sputo venti versi col flow particolare
    Così se li senti posso farti volare
    Pompa questi, esci e molla gli altri, compare, eh?
    Metto la palla in buca
    C'ho il numero 9 come Batistuta
    La mia gente parla di merda perché l'ha vissuta
    Per questo quando ti sento ogni mio frà ti sputa
    Aumento l'alimentazione, prende fuoco l'alimentatore
    Chi si inventa storie gli sputo a rallentatore
    Ogni sei parole ti do dipendenza come il metadone
    Metà uomo metà clone
    Faccio il seratone
    Sotto il segno del dragone
    Scrivo ogni sera nuove barre
    Che per farle impieghi il tempo che il pianeta muore
    Frate' di 'sta merda mi hanno appena eletto il senatore
    Frate' di 'sta merda mi hanno appena eletto imperatore!
    Quando monto sembra di stare in un altro mondo
    E pensa che non ci faccio manco molto
    Rimando tutti a casa finché gratto il fondo
    Flow killer, drug dealer
    Non pensare che finisco, ne ho mille
    No macchine, no ville
    Che te pensi che ho firmato con Skrillex?
    Siamo Tanta Roba! (tanta Roba!)
    Il triangolo a.k.a. gli altri artisti piangono (scusa!)
    Dani sai quanti dischi mancano? (uh!)
    Che prendo una barca con tre grammi infilati dentro la scarpa
    Sto coi miei fratelli che l'accendono all'alba
    Non amo la strada perché vengo da là, frà (ciao!)
    Le tecniche che cerchi tu, c'ho
    Seh, faccio un pezzo sopra al bumcha da denuncia
    Te ti brucia che spacco pure se sbaglio la pronuncia
    M un colpo di Mauser, tu un Taser
    Quante barre scrause che fate
    Vi consiglio delle pause
    Piangi in ogni singolo, sembra che hai la sindrome di Münchhausen
    Le rime che cerchi non le spunto, le archivio
    Fai cagare quando rappi in studio e dal vivo
    Se mi spari torno, sono vendicativo
    Living dead, Mad il vampiro
    Torno dalla morte, da Caronte
    Sale dalle catacombe, scala il monte
    Il tuo bro scappa forte, sbarra porte
    Perché sa che il mio flow è una Colt e spacca calotte
    Spingo troppo finché doppio il suono
    Fumo l'oppio e chiudo gli occhi, Hiroshima
    Scavo tombe tipo l'Etna
    Salgo in vetta, sgancio bombe tipo Vietnam, Indocina
    Scemo impara la gavetta, tirocina
    Ci ricopiano a manetta, tipo Cina
    Li mangiamo tipo M&M's
    M e Gem sono tipo Rei e Kenshiro, voi Shiro e Mila
    No io non finisco, sennò questi dicono che non ho voglia
    Fanno come quella tipa che non dice che è una troia
    Poi si ingoia i miei coglioni come dei ravioli
    Perché dice sì come a Valsoia
    Quando me li ingoia mentre guido metto la seconda
    Lei che mi asseconda, mi diventa tipo una sequoia
    Mentre bevo Cognac, cazzo che vergogna
    Da mezz'ora giro a 'sta rotonda
    Ogni barra è un missile balistico di Putin
    Ho lo stile fisico, quantistico, ti chiudi
    Per rifarlo pure se è impossibile ne ho visti tributi
    Rappo per altri venti minuti
    Metricamente autistico, avanguardistico
    Ho fatto lo scientifico, mica l'artistico
    Sto con Labadini, gonfio Napapijiri
    Davide di là che gira papiri
    Cappa nella stanza
    Fissiamo la ganja che ci pa-ra-lizziamo
    La faccia pessima ma ma-ciniamo la traccia a pezzi
    Guarda chi siamo
    Non guardo i prezzi frate'
    Acquistiamo altri quattro pezzi di Pakistano
    Ci ribaltiamo gli occhi al contrario
    Che ti battiamo è lapalissiano
    Sto a mille!
    Guardami che brucio le papille
    Sulla base non indugio: serial killer
    Voglio demolire, che ti devo dire?
    Voglio solo morire alle Antille
    Non mi voglio accontentare
    Rappo tipo lama per accoltellare
    Ogni barra è la mia dama da contemplare
    Da domani Ramadan, non rompe' pare
    Frà c'ho la madama che è pronta a entrare!"
        ],
        [
            "name"=>"ansia no",
            "artist" => "FSK Satellite",
            "key" => "C♯ major",
            "bpm" => 160,
            "duration" => "2:29",
            "release date" => "2019-07-12",
            "album" => "FSK Trapshit",
            "immagine"=>"./images/ansiaNo.jpg",
            "lyrics"=>"
    Ansia no, ho fatto due soldi, ho detto \"Bianca stop\"
    Dopo due secondi Polo Nord
    A casa c'ho il Polo Nord, eh, appresso c'ho il Polo Nord
    Dentro il bomber di Moncler che fa più luce, il Polo Nord
    E sai che ho detto ansia no
    Ho fatto due soldi, ho detto \"Bianca stop\"
    Dopo due secondi Polo Nord
    A casa c'ho il Polo Nord, eh, appresso c'ho il Polo Nord
    E dentro il bomber di Moncler che fa più luce, il Polo Nord
    E sai che ho detto ansia no,
    Ho fatto due soldi, ho detto \"Bianca stop\"
    Dopo due secondi Polo Nord
    A casa c'ho il Polo Nord, eh, appresso c'ho il Polo Nord
    Dentro il bomber di Moncler che fa più luce, il Polo Nord
    Quando entro nel club sembra il Polo Nord
    Polo Ralph Lauren (Ralph Lauren), Amiri o Balmain
    Sto fumando cookie da cinque euro al G, stelle Givenchy
    Ciabattine Armani, Taxi B, Gucci e Fendi
    Spostavamo pacchi, ora alziamo stipendi
    Siamo il boss del trapshit (Ollare the gang)
    Pa-pa-pa-pa, parlo canna o crack, sip-, sippo lean
    Per la tua tipa sono benzodiazapina, ehi
    La bagno come un nacho, sì
    Mi, mi, mi chiama gotico
    Se poi è un pompino, ho sprecato un emoticon
    Oppure due o tre, oppure che vuoi?
    Sai che lo faccio col gang, mica lo faccio con te
    Ta-ta-taxi e FSK uguale a la trap in Italia
    Ne abbiamo chiusi più cinquanta in banca solamente al primo album
    A casa c'ho il Polo Nord, eh, appresso c'ho il Polo Nord
    E dentro il bomber di Moncler che fa più luce, il Polo Nord
    E sai che ho detto ansia no
    Ho fatto due soldi ho detto \"Bianca stop\"
    Dopo due secondi Polo Nord
    A casa c'ho il Polo Nord, eh, appresso c'ho il Polo Nord
    E dentro il bomber di Moncler che fa più luce, il Polo Nord
    Fuck Sprite clean, non raccolgo il cash
    Drip dentro al club con la gang, siamo i boss
    Uno, due, tre, bianca stop, ansia no
    Mi inseguono bitch, ice, nuovo Moncler
    Non ho più freddo, mamma, no più ansia, grazie
    Madonna redimi i peccati grazie
    F, S, K, sto lanciando il cash
    Back nel privé, double cup, siamo i boss
    A casa c'ho il Polo Nord, eh, appresso c'ho il Polo Nord
    E dentro il bomber di Moncler che fa più luce il Polo Nord"
        ],
        [
            "name"=>"Server",
            "artist" => "Sadturst, KIID, Ghali e Thasup",
            "key" => "C♯ major",
            "bpm" => 124,
            "duration" => "2:49",
            "release date" => "2025-07-25",
            "album" => "NRM2",
            "immagine"=>"./images/Server.jpg",
            "lyrics"=>"
    SadTurs, ahahah
    Ahahahah
    Yeah, yeah
    KIID, are you ready? Facciamolo (Let's do it)

    [Ritornello: thasup]
    Sono dentro al server, non mi fotti un'altra volta, yah
    Fumo sempre il verde, così sono sempre verde, bruh
    Mixo come Dexter 'ste pozioni, mi fanno più trap
    Siete niente, niente di niente di niente

    [Strofa 1: thasup]
    Skippo questa gente, faccio swipe left, swipe right
    Tu sei un meme, meme, fai il pendente, ma con zero ice
    Questa gente mente perché vuole prender sempre like
    Siamo steppers, steppers, la merda sta sotto le mie Nike
    Yeah, ho una bitch più chic e una bitch di strada
    Quella baddie lì, no, non l'ha imparata la lezione, damn
    Sono sempre sciallo, ma sto sempre in para
    Bro, quel maresciallo me l'ha sequestrata, povero me
    Non ho mai fatto lo snitch, nev-never (Yeah)
    Scopo 'sta bitch e sembra un ASMR
    'Sta roba è tipo sopra il next level (Livello in più, è di un livello in più), yeah
    Non ho capito questo press nel cell
    Si vede in viso che sei un trash flexer


    [Ritornello: thasup & Ghali]
    Sono dentro al server, non mi fotti un'altra volta, yah
    Fumo sempre il verde, così sono sempre verde, bruh
    Mixo come Dexter 'ste pozioni, mi fanno più trap
    Siete niente (Sto), niente di niente di niente (Sto)

    [Bridge: Ghali]
    Ahahahah
    Ahahahah
    (Eins, zwei, drei)

    [Strofa 2: Ghali]
    Hermès, la metto nel cesto del Lime (Ah)
    Più non esco e più sono in hype
    Hermès, la metto nel cesto del Lime
    Lei mi dà un bacio che, muah, sa di white
    Lei è tutta bagnata, mi sa che vuole raffreddare il server, ehi
    Chi pensa che stai spaccando, ah, crede all'11 settembre (Ahahah), ehi
    Mixo un po' questo e un po' quello, ah, come se fossi un DJ, ehi
    Ah, gli ho scopato la tipa solo perché mi ha commentato: \"Gay\" (Ahahah)
    Oh mio Dio, come sto? (Sto) L'ho mandata giù intera
    Leggings le fa il camel toe, la chiamo Margiela (Sto)
    [Outro: thasup]
    Sono dentro al server, non mi fotti un'altra volta (tha Supreme), yah
    Fumo sempre il verde, così sono sempre verde, bruh
    Mixo come Dexter 'ste pozioni, mi fanno più trap
    Siete niente, niente di niente di niente "

        ],
        [
            "name"=>"kiSs",
            "artist" => "Yungest Moonstar e Thasup",
            "key" => "A♯ minor",
            "bpm" => 140,
            "duration" => "2:40",
            "release date" => "2024-07-26",
            "album" => "Sfaciolate MixTape pt.1",
            "immagine"=>"./images/kiSs.jpg",
            "lyrics"=>"
     Yeah, bugiardi scrivono commedie
    I veri sopra ci rideran
    So che dà fastidio correre
    Ma corro per quelle volte che non l'ho fatto
    Sogno un bastardo in polvere
    Poi la trasformo in polvere, ma da sparo
    Così shotto senza soccombere
    Sembrate puttane che vogliono un bacio
    Non voglio kiss da una bitch
    Da una bitch, da una bitch
    Non voglio kiss da una bitch
    Da una bitch, da una bitch (yeah, yeah)
    Falla come fosse un drago
    Malloppo nelle tasche come i narcos
    Fa l'occhio dolce se non la calcolo
    Belli e buoni da fuori, tipo una bacca
    Vieni e muori se provi a fare la barca
    E sembri un cazzo di gommone in spiaggia
    Bеstseller, le taschе ce le ho un po' piene
    Ma non di conchiglie per la tua ragazza
    Sto fumando due blunt pieni d'erba a sfaso
    Non so come, bro', mi ci son trovato
    Viaggio da Roma a Tokyo, poi giù in Alaska
    Dalle dune di Shan volo in Colorado
    'Sto viaggio ad M-I l'ho colorato
    Pensavi che mi sarei abituato
    Ma non fotto con NPC 'sta volta
    Quella troia non sa che ho dimenticato, ripeto che
    Yeah, bugiardi scrivono commedie
    I veri sopra ci rideran
    So che dà fastidio correre
    Ma corro per quelle volte che non l'ho fatto
    Sogno un bastardo in polvere
    Poi la trasformo in polvere, ma da sparo
    Così shotto senza soccombere
    Sembrate puttane che vogliono un bacio
    Non voglio kiss da una bitch
    Da una bitch, da una bitch
    Non voglio kiss da una bitch
    Da una bitch, da una bitch (yeah)
    Se te l'ha fatto papi non lo puoi flexare
    Ah, non vale un cazzo, scappi se lo fan notare
    Prendine atto, homie, che sei cringe a merda
    Mi ricordi un sacco tutte 'ste puttane
    Quando voli in alto, ti voglion fermare
    Poi, se cadi in basso, chissà chi rimane
    Solo scacco matto, fare sfaciolate
    Ci ho messo un po' d'anni perché stavo fatto
    Scusa, brodie, se t'ho dato un altro pacco
    Ma non lo faccio apposta, non l'ho fatto apposta
    'Sta roba t'intoppa, zero sbatti, sblocca
    Tu sei tutto ossa, chiudi quella blocca
    Pussy fa carriera con la sua bocca
    Mi sembrava strana, infatti, quella borsa
    Okay, ci hai fatto i money, ma a quale prezzo?
    Scusa se disprezzo, ma mi fate noia, giuro
    Bugiardi scrivono commedie
    I veri sopra ci rideran
    So che dà fastidio correre
    Ma corro per quelle volte che non l'ho fatto
    Sogno un bastardo in polvere
    Poi la trasformo in polvere, ma da sparo
    Così shotto senza soccombere
    Sembrate puttane che vogliono un bacio
    Non voglio kiss da una bitch
    Da una bitch, da una bitch
    Non voglio kiss da una bitch
    Da una bitch, da una bitch"
        ],
        [
            "name"=>"marymango",
            "artist" => "Thasup e Ghali",
            "key" => "A♯ minor",
            "bpm" => 81,
            "duration" => "3:25",
            "release date" => "2020-05-08",
            "album" => "DNA",
            "immagine"=>"./images/marymango.jpg",
            "lyrics"=>"
    Ok (ok)
    Sai che
    Sooo-noo fa-ha-hatto, ha ha ha bro
    Fuck tutti quelli che
    Sooo-noo fa-ha-han tuoi affari tuoi, affari tuoi
    Soo-noo fa-ha-hatto, ha ha ha bro
    Fuck tutti quelli che
    Sooono fa-ha-han tuoi ha ha ha ha boy
    Ha ha ha ha ha boy
    Sorridi qui in camera che è candid (sì)
    Nu-nu-nuove Lelly Kelly, Candy Candy (Candy)
    Ho tre amici e il resto sono conoscenti (conoscenti)
    Erba alta che non vedo più i serpenti (serpenti)
    Sopra l'onda come un pazzo con il jet ski
    S-s-sai già che col c- che mi prendi
    Questo contratto è troppo basso fra mi offendi
    Sono stanco e ho bisogno di un happy ending
    Sono le tre
    Di notte sto pensando ancora a me
    Buona eh
    L'ho presa da me (mandami in rec)
    La sto pressando con un cavo jack (yee)
    Sai che
    Sooo-noo fa-ha-hatto, ha ha ha bro
    Fuck tutti quelli che
    Sooo-noo fa-ha-han tuoi affari tuoi, affari tuoi
    Soo-noo fa-ha-hatto, ha ha ha bro
    Fuck tutti quelli che
    Sooono fa-ha-han tuoi ha ha ha ha boy
    Ha ha ha ha ha boy
    Sono sotto come con il black magic
    Non mi fermo sembro un Redbull con i piedi
    Scarpa limitata tutte cascano ai miei piedi
    Ho speso più gambe di un cazzo di millepiedi (no che non mi vedi) ey
    Anzi ora mi vedi (bling)
    Ho anelli come Yury Chechi
    Son gioielli, trofei per gli atleti
    Ho la casa grande come i preti
    Tu non vuoi bitch
    Ma vuoi un appiglio
    Trovarlo fra è easy
    Tenerselo no tene
    Tenerselo no tene
    Quello che dico in tele
    Televisione, non te lo dicono
    Mamma mister guarda quanti clichè
    Mami guarda sti rapperirini sto col mixer
    I miei fan, fan ya
    E tu chi mi diss fre
    Leggi riviste
    Cose viste e riviste
    Bravo un bel quickscope
    Sopra sto reggaeton
    Non vedo l'ora direi mo stop
    Non chiedo broda madò che accollo
    Sono loco loco loco lo-lol-lol (lo-lol-lol lol)
    Tipo il Willy Wonka del flow
    Hai finito ma dai bro col teatrino
    Non ti vorrebbero neanche in show (vuoi farmi)
    Vuoi farmi fuori ma rimango
    Sto fumando Marymango
    Vuoi farmi fuori ma rimango
    Sto fumando Marymango
    Vuo-vou-vuoi farmi fuori ma rimango (ma rimango)
    E sto fumando Marymango (Marymango)
    Vuoi farmi fuori ma rimango (ma rimango)
    E sto fumando Marymango (Marymango)
    Vuoi farmi fuori ma rimango (ma rimango)
    E sto fumando Marymango (Marymango)
    Vuoi farmi fuori ma rimango (fuori ma)
    E sto fumando Marymango"
        ],
        [
            "name"=> "Perdonami",
            "artist" => "Salmo",
            "key" => "F♯ major",
            "bpm" => 77,
            "duration" => "2:14",
            "release date" => "2017-11-27",
            "album" => "Playlist",
            "immagine"=>"./images/Perdonami.jpg",
            "lyrics"=>"
    Se dico quello che penso
    Non resta neanche un amico
    Sono una merda, confesso
    Se penso a quello che dico (Ah)
    Perdonami (Yeah), perdonami (Yeah)
    Perdona, perdona, perdonami (Ah)
    Perdonami (Yeah), perdonami (Yeah)
    Perdona, perdona, perdonami (Ehi)
    I rapper di ora si vestono male (Yeah)
    E cantano male (Yeah)
    E più fanno schifo, più sale la fama (Yeah)
    Ti sembra normale? (Ah)
    È come se adesso ti vomito in faccia (Yeah)
    Ti passa la fame (Ah)
    Le tipe che schiacci non le farei
    Toccare neanche dal cazzo del cane (Ehi)
    È meglio se fuggi (Ah)
    Tu non c'hai la stoffa bro', taglia e ricuci (Ah)
    In Italia nessuno lavora, ma rubano in casa e poi vanno da Gucci (Uh)
    E cazzo ti ostenti (Uh) se vivi di stenti (Ehi)
    Sei un tipo stipato che sogna stipendi (Ehi)
    Staccare gli assegni
    Pirata ai Caraibi (Ah)
    Ho un flow da karate, ti levo i carati dai denti (Ah)
    Uno schiaffo e ti svegli
    Problemi al cervello, bro', spegni e riaccendi, spegni e riaccendi
    Sabato sera (Brr)
    Dopo le quattro hai la faccia di cera
    Vacanze in riviera
    Leccando una figa pisciata che sa di ringhiera
    Chi accende le radio è un over 50, si pompa gli Stadio
    Poco evoluto, va ancora allo stadio
    Un vero cornuto non guarda mai dentro l'armadio
    Male, male? Tutto bene, no?
    Male, male? Tutto bene, no?
    Male male, male male, male male, ehi (Ehi)
    Scrivo piu chiaro in possibile (Ah)
    Se non capisci, riassumo (Yeah)
    Bravo, hai una mira infallibile (Ah)
    Ma non colpisci nessuno (Ehi)
    Perdonami (Yeah), perdonami (Yeah)
    Perdona, perdona, perdonami (Ah)
    Perdonami (Yeah), perdonami (Yeah)
    Perdona, perdona, perdona
    Perdona il peccato (Uh)
    Ricorda il mio nome (Ah)
    Sei il tipo sfigato che sogna di fare l'attore
    Peccato sei quello che muore (Ah)
    Fa-fa-farò la veglia (Ah)
    Quando suona la sveglia (Ah)
    Io non posso andare in tele', perché se ci vado
    Poi mi parte la bestemmia (Oh, ma porco D-)
    Pardonne moi, pardonne moi
    Hai fegato, bruh, patè de foie
    Se riesci a distinguerti in questa città
    Sei come una zebra a pois (Yeah)
    Anche se smetto col fumo (Ah)
    Ti ascolto, mi sembri qualcuno (Yeah)
    Scusa la spocchia, io sono uno
    Voi centomila, nessuno (Ehi)
    Se dico quello che penso
    Non resta neanche un amico
    Sono una merda, confesso
    Se penso a quello che dico (Ehi)
    Perdonami (Yeah), perdonami (Yeah)
    Perdona, perdona, perdonami (Ah)
    Perdonami (Yeah), perdonami (Yeah)
    Perdona, perdona, perdonami (Ehi)
    Scrivo più in chiaro possibile (Ah)
    Se non capisci, riassumo (Yeah)
    Bravo, hai una mira infallibile (Ah)
    Ma non colpisci nessuno (Ah)
    Perdonami (Yeah), perdonami (Yeah)
    Perdona, perdona, perdonami (Ah)
    Perdonami (Yeah), perdonami (Yeah)
    Perdona, perdona, perdonami (Ehi)"
        ]
    ];
