<?php

    $users = array (
        "MatWasTaken" => array (
            "name" => "Matteo",
            "surname" => "Veronesi",
            "age" => 18,
            "password" => "1234",
            "accesses" => 0
        ),
        "SimonSays" => array (
            "name" => "Simone",
            "surname" => "Ceschi",
            "age" => 18,
            "password" => "5678",
            "accesses" => 0
        ),
        "TheGreat" => array (
            "name" => "Giuseppe",
            "surname" => "Rossi",
            "age" => 20,
            "password" => "IAmGreat",
            "accesses" => 5
        ),
        "Thasup" => array (
            "name" => "Davide",
            "surname" => "Mattei",
            "age" => 24,
            "password" => "0hG0d238451",
            "accesses" => 7
        ),
        "Guest" => array (
            "name" => "Guest",
            "surname" => "",
            "age" => 0,
            "password" => "",
            "accesses" => 0
        ),
        
    );
    